### ISSUE TITLE
Not sending data or saving session

### ISSUE THREAD

**Issue by kevin192291** [JackGruber/esp32_ttn_environmental_sensor#1]
Hello,
I am attempting to run this on a Heltec v2 lora board.
The issue is that it connects, then fails to send any data, sleeps, and re-connects. Running the LoraWANDebug(RTC_LMIC);
displays this:
```
LMIC.opmode: 
LMIC.seqnoUp = 0
LMIC.globalDutyRate = 0 osTicks, 0 sec
LMIC.globalDutyAvail = 0 osTicks, 0 sec
LMICbandplan_nextTx = 525736 osTicks, 8 sec
os_getTime = 527196 osTicks, 8 sec
LMIC.txend = 525736
LMIC.txChnl = 5
Band 	avail 		avail_sec	lastchnl 	txcap
0	0		0		0		0
1	0		0		5		100
2	0		0		0		0
3	0		0		0		0
```
and seqnoup is always 0, dispite successfully authing with TTN.
It may be worth mentioning that I am on the AS923 JP freq.

Any idea why it will not send? Could it be the AS freq that it isn't liking?
I don't have a US Gateway so I can't test with 915mhz.

Thanks for the help! I would really love to use this code!!!!

I should add that with the same settings, the https://github.com/mcci-catena/arduino-lmic does send data without a problem.

**Comment by JackGruber** [comment]
Could you post a complet output from the console. 
On 915 Mhz is my workaround for the DutyCycle not working. Possible this is also on AS923.

**Comment by kevin192291** [comment]
Thanks for that really fast reply!
Here is a fully cycle of the output:
```
225664: EV_TXSTART
Runtime: 5 seconds
590524: EV_JOINED
netid: 0
devaddr: 192AFFB
artKey: C7BAF96796914A372ABBA1D5503324
nwkKey: A54B14134193F8289C669DF7974D8D
590547: EV_TXCOMPLETE
Go to DeepSleep ...
Runtime was: 9 seconds
Save LMIC to RTC ...
0


LMIC.opmode: 
LMIC.seqnoUp = 0
LMIC.globalDutyRate = 0 osTicks, 0 sec
LMIC.globalDutyAvail = 0 osTicks, 0 sec
LMICbandplan_nextTx = 590517 osTicks, 9 sec
os_getTime = 591976 osTicks, 9 sec
LMIC.txend = 590517
LMIC.txChnl = 4
Band 	avail 		avail_sec	lastchnl 	txcap
0	0		0		0		0
1	0		0		4		100
2	0		0		0		0
3	0		0		0		0




```
I am not sure if that helps at all. That is what I am seeing in my serial out.

**Comment by JackGruber** [comment]
Hm ...
Join is ok and a msg was send. Then a seqnoUp of 1 should be saved ...
But in the output the seqnoUp is 0 and the EV_TXCOMPLETE event says data was send. 
Could you try the code from https://github.com/JackGruber/ESP32-LMIC-DeepSleep-example only for testing the DeepSleep

**Comment by kevin192291** [comment]
Yes! Actually I have,
I got the same exact result!
Here is what I am seeing on TTN side:
![tts err](https://user-images.githubusercontent.com/15717216/104958000-3fcbf200-599d-11eb-9988-c2acbef12118.png)
but never any data
When I run the arduino-lmic example `ttn-otaa` it seems to take a fair amount of time between showing `EV_TXCOMPLETE` and the data to display in TTN console. I am wondering if the code may be going to sleep too fast?

**Comment by JackGruber** [comment]
> Code that accesses the content of the LMIC structure may need to be modified, as some of the fields have been renamed, or rearranged.

From the LMIC changelog ...

I think the codeneed a rework to run with lmic > 3.0.99
You can try it with the version 3.0.99

**Comment by kevin192291** [comment]
Just to be clear, It is the https://github.com/mcci-catena/arduino-lmic version of the library right?
I get MAX_BANDS being missing on version 3.0.99 (if installed from the library manager) and all versions of 3.0.99.x if
I download the zips from github, also, Anything before 3.0.0 and I get missing case items such as `case EV_RXSTART` and `case EV_JOIN_TXCOMPLETE`
If there is anything I can do to assist getting this working, I would absolutely love to help. This seems really really important for LoRa nodes!!!

**Comment by JackGruber** [comment]
OK, I have checkt my projects. 
I use the LMIC version 3.1.0, 3.2.0, but it works also fine with 3.3.0.

>Just to be clear, It is the https://github.com/mcci-catena/arduino-lmic version of the library right?

Yes, I saw you have opened an issue there too.

**Comment by kevin192291** [comment]
Sounds good. I Think the issue I opened on the Arduino-lmic page may be a bit different.
I figure I will try to handle the re-join and the data sending separately. Thanks, I will keep trying on these. I appreciate the support!
